spring:
  application:
    name: siacon
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver 
    
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8080
